### PR TITLE
Refactor config code

### PR DESCRIPTION
**Pull request by michaelosthege**
### Changes
+ 16/32/64 are no longer supported as aliases for float16/float32/float64
+ removal of already deprecated config options
+ API of the `ConfigParam` was changed - it is however only used by `configdefaults`. I refactored the `ConfigParam` and related types such that they all support...
  + an `apply` function that casts or modifies parameter values upon assignment (e.g. replacement of `~` with user home dir)
  + a `validate` function that checks if a parameter value is valid (e.g. checking the availability of a GPU device)

### ToDo-List
+ [x] ~not importing other parts of the codebase~ deferred to follow-up PR (see [comment](https://github.com/pymc-devs/Theano-PyMC/pull/201#issuecomment-737776450))
  + [x] dependency on `theano.Mode` was replaced with an `__mro__` inspection
  + [x] ~`theano.gof` dependency is still there because the config tries to invoke it to learn about compilation flags.~ deferred to follow-up PR (see [comment](https://github.com/pymc-devs/Theano-PyMC/pull/201#issuecomment-737776450))
+ [x] tests for contextual changes of parameters
+ [x] get rid of dot-based section delimiters - replace with double underscore delimiters (`HISTORY.rst` was left unchanged)
+ [x] refactor `configdefaults` such that things are done via functions and not at import-time

### CODE REVIEW

**Comment by michaelosthege** [comment]
@brandonwillard the dependency on `theano.gof.cmodule` is because the `configdefaults` attempts to invoke GCC to learn about config flags.
* Do you intend to refactor the `GCC_compiler` linker to make them it more orthogonal?
* Can/should we move all the `theano.gof.cmodule`-related addition of config settings to `theano.gof.cmodule`?

**Comment by brandonwillard** [comment]
> * changing "THEANO" to "AESARA" for the environment variables and the like

We might not want to make this PR dependent on that change, especially since there's a lot of other things that would then be required to merge this without having a weird Theano/Aesara mix.  If you don't mind waiting for those other changes to merge this, then it's not a problem.

**Comment by michaelosthege** [comment]
> > * changing "THEANO" to "AESARA" for the environment variables and the like
> 
> We might not want to make this PR dependent on that change, especially since there's a lot of other things that would then be required to merge this without having a weird Theano/Aesara mix. If you don't mind waiting for those other changes before merging this, then it's not a problem.

Good point. It will be best to do the rename for all of the codebase at the same time - not in this PR. 

What about the other dependency though?

**Comment by brandonwillard** [comment]
> * Do you intend to refactor the `GCC_compiler` linker to make them it more orthogonal?

Yes.  Improving orthogonality and reducing coupling is one of&mdash;if not _the_&mdash;primary goal of our Theano refactoring efforts in general.  

I'm not sure if the `GCC_compiler` module itself suffers too much from either of these, but I can believe that other modules that use it do.  From a quick inspection, I don't see any module-level uses of `theano.config` (i.e. the kind that would require `theano.config` at import time) besides the import of `theano.config` itself.

> * Can/should we move all the `theano.gof.cmodule`-related addition of config settings to `theano.gof.cmodule`?

That does sound better, but there might be a few references to `theano.config.cmodule` in other modules that could make that move difficult and/or not a great advantage (yet, at least).  It's those module-level/import-time `theano.config` reference that really hurt the project.

**Comment by brandonwillard** [comment]
> * dependency on `theano.Mode` was replaced with an `__mro__` inspection

That's an interesting workaround, but it should be possible for us to use `Mode` at any stage of the import process if we just put it into its own module, no?  There are often package-level imports that precede and foil these kinds of simple fixes, but those imports can (and should) often be refactors/removed as well.

Even if those refactorings are too complex to do here and now, we can always create a simple "interfaces" module and/or sub-package that only serves to provide classes for simple type checks and the like, if that's all that's needed in this case.

**Comment by michaelosthege** [comment]
@brandonwillard while the import cycles are still there, the diff is already quite hard to look at.
I intend to continue improving the following aspects, but would prefer to do it on a follow-up PR:
+ refactor such that there are less global variables (or at least such that they are attributes of the same singleton
+ replace the `__get__` / `__set__` monkeypatching with real `@property` and methods
+ make the singleton `config` object explicit, such that we can test with `testconfig` instances instead of the real thing (also touches the global dict variables)

After this PR, it becomes a lot easier to do the following - preferably on separate PRs:
+ removal of a bunch of deprecated/outdated/experimental config settings
+ re-organization (re-naming?) of configvars such that their grouping in the `add_*_configvar()` functions makes sense
+ re-organization of `add_*_configvar()` functions and where/when they are called to get rid of cyclic dependencies

Do you agree with this roadmap? If it would be great to merge this one so the follow-ups can get nicer diffs.

**Comment by brandonwillard** [comment]
> Do you agree with this roadmap? If it would be great to merge this one so the follow-ups can get nicer diffs.

If the each logical unit of change is too large to be a single commit, then, yes, we should break this up into separate PRs.

I'll take a look at the changes in this one, but currently it looks like we need to squash some "fix" commits into the commits containing their original changes (e.g. commits that fix formatting issues should be merged into the commits that introduced the issues).  

If you want, I can restructure those commits as I review the changes.

**Comment by brandonwillard** [comment]
I just pushed some changes to the commit structure, so be sure to rebase locally.

**Pull request merged**
