### PR TITLE
Use black formatting and update code style and conventions

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR applies `black` formatting and adds a formatting check to Travis.  It also removes an unnecessary custom `flake8` test runner script, applies some `flake8`-based style changes, and simplifies the use of `flake8` on this codebase.

### CODE REVIEW

**Comment by twiecki** [comment]
Thank! Should wait for CI to be set up so that we know this didn't break anything.

**Comment by brandonwillard** [comment]
> Thank! Should wait for CI to be set up so that we know this didn't break anything.

It was passing in CI before the rebase and recent commits.  I'll put it in draft-mode for now, though.

**Comment by twiecki** [comment]
If you run tests locally and they pass then we should merge, these kind of PRs get stale quick.

**Comment by dfm** [comment]
I'm finding some unit test failures on this branch that I wasn't finding before so I'll try to diagnose and report back!

**Comment by brandonwillard** [comment]
> I'm finding some unit test failures on this branch that I wasn't finding before so I'll try to diagnose and report back!

Yeah, I'm still rebasing here and there, so keep an eye out for that.

**Comment by dfm** [comment]
@brandonwillard: sounds good! Let me know if there's anything that I can do to help and when it's ready!

**Comment by brandonwillard** [comment]
All right, the standard tests seem to be in order, but I can't say much about the GPU-requiring ones.

**Pull request merged**
