### PR TITLE
Jax ops doc

### PR DESCRIPTION
**Pull request by canyon289**
Draft notebook to address https://github.com/pymc-devs/Theano-PyMC/issues/230

Could use a double check for tone and concept correctness. If those two are good I'll sweep through for grammar and spelling.

### CODE REVIEW

**Comment by twiecki** [comment]
This is great - thanks @canyon289! I think the explanation of what each line in the test does could help.

**Comment by canyon289** [comment]
Thanks for feedback, will make edits in next ~16 hours

**Comment by canyon289** [comment]
Added more comments. The last remaining question I have from my end is should we call things Theano-PyMC or Aesara in the doc? I'm inclined to write Aesara so we don't have to change it later. Happy to take opinions as always

**Comment by twiecki** [comment]
Agree with naming it Aesara.

**Review by brandonwillard — CHANGES_REQUESTED** [review]
These additions are more suitable as documentation in `doc`.  Can you replace this with a `.txt` in `doc/tutorial`?

**Comment by canyon289** [comment]
Should the .txt be formatted as rst file? Looking at others it seems like thats the case, but not so secretly hoping I dont have to deal with rst

**Comment by brandonwillard** [comment]
Yes, I believe those files are supposed to be reStructuredText.  We should probably create a ticket for renaming them to `.rst`.

**Comment by canyon289** [comment]
This is larger than this pr but could we also, not use rst or transition to markdown, or myst markdown or something? Would this be something open for discussion?

**Comment by brandonwillard** [comment]
I don't want to instigate any potentially large efforts to convert the existing RST documents into a new form of Markdown, at least not without some major benefits that outweigh the cost of learning a well established syntax like RST.  The same goes for inviting a patchwork of syntaxes by adding support for a new one; that only increases the maintenance burden.

**Comment by canyon289** [comment]
Sounds good. Ill get this changed over "sometime soon" to rst. Thanks for the review

**Comment by twiecki** [comment]
@canyon289 I think there are tools to easily convert ipynbs to rst.

**Pull request closed without merging**
