### PR TITLE
Combining checks into one and dealing with skipped runs

### LINKED ISSUE #87: Simplify/combine status checks
Our CI workflow sets up a bunch of independent jobs via the matrix settings, and each one of those creates a possible status check under this repo's branch protection settings.  It would be better if we had a single job that could serve as a status check for all the matrix jobs, especially as we add/remove jobs via the matrix settings (e.g. new Python versions).

So far, [this](https://github.community/t/status-check-for-a-matrix-jobs/127354/7?u=brandonwillard) was the best advice I could find; it says to create a new job that simply checks the matrix build status.

### PR DESCRIPTION
**Pull request by dfm**
I believe that this will fix #87.

I'm finding that some of the jax tests are failing on my fork though:

`tests/sandbox/test_jax.py::test_extra_ops` fails with:

```
jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.
```

### CODE REVIEW

**Comment by dfm** [comment]
Also: I that the only way to totally fix #87 will be to make the coverage check not required.

**Comment by brandonwillard** [comment]
> Also: I that the only way to totally fix #87 will be to make the coverage check not required.

The latter part of #87?  If so, I'm fine dealing with the uncompleted checks if fixing it means disabling the coverage requirement, because we're really gonna need to enforce the coverage checks as development starts ramping up.

**Comment by brandonwillard** [comment]
> I'm finding that some of the jax tests are failing on my fork though:

Hmm, not good; I'll check that out.

**Comment by dfm** [comment]
Yeah - that's what I meant! I don't think that we can have the coveralls report be a required check if we're not going to run the tests for some pull requests because coverage won't be reported for those cases. It'll still show up as a failure on the pull request, but merging won't be blocked.

This PR is ready for review now, I think. It adds an "All tests" check that reports the results of all the matrix builds. Once the action finishes running, we can make that the required check.

The jax test [is still failing](https://github.com/pymc-devs/Theano-PyMC/runs/1221895180?check_suite_focus=true), but this pull request can't have caused any of those so I'm a bit confused.

**Comment by brandonwillard** [comment]
> The jax test [is still failing](https://github.com/pymc-devs/Theano-PyMC/runs/1221895180?check_suite_focus=true), but this pull request can't have caused any of those so I'm a bit confused.

My guess is that it has to do with some (effectively) random test values.

**Comment by brandonwillard** [comment]
Nope, I was wrong, it's due to a recent `jax`/`jaxlib` update!

**Comment by brandonwillard** [comment]
Relevant issue: #89

**Comment by brandonwillard** [comment]
Are we uploading the coverage for every matrix job?

**Comment by dfm** [comment]
Yes, but those don't get displayed on coveralls until the final job where coveralls is told to "finish" and combine all the steps. This is the recommended procedure for coveralls on actions.

**Comment by dfm** [comment]
@brandonwillard: In response to your implied concern I switched to merging the coverage results in place and then uploading them once. That way the "checks" tab doesn't get spammed. It looks like it worked so this should be good to go.

**Comment by brandonwillard** [comment]
> I switched to merging the coverage results in place

Many thanks!  It doesn't appear to be a real problem, but it is a bit jarring in some ways.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
