### PR TITLE
Fix subtensor shape inference

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR adds generic shape inference for basic and advanced NumPy indexing on Theano tensors.

Note: the boolean case isn't covered, yet.

### CODE REVIEW

**Comment by brandonwillard** [comment]
Currently, I'm stuck considering whether or not we should attempt to use `tt.nonzero` to convert boolean indices into "regular" non-boolean indices.  This seems to work rather well and cuts down the amount of boolean-specific logic need in the `*Subtensor*` `Op`s (it also entirely obviates some `Subtensor` `Op`s); however, it has one distinct disadvantage: it doesn't produce the same (runtime) errors as NumPy.

This can arise when `nonzero` reduces the dimension size of the boolean indices so that they actually match an indexed array with smaller dimensions.  When this happens, the `Op.perform` will succeed without error, yet the corresponding NumPy operation would fail.

We could use an `Assert` node that will raise an exception when the dimensions of the boolean indices and the indexed array do not match, but, unfortunately, this exception wouldn't match NumPy's exception type.  Also, `Assert` nodes can be removed during certain forms of optimization, and we wouldn't ever want to remove these ones.

**Comment by twiecki** [comment]
I don't see the numpy-incompatibility here as a blocker and the assert node (even with a different exception) is a reasonable solution.

**Comment by brandonwillard** [comment]
This PR has grown to include quite a few independently important changes that were needed along the way&mdash;as well as some helpful refactoring.  Due to the general importance of these changes, I'm going to consider this PR finished once the tests pass and continue the boolean indexing changes in another PR.

**Comment by brandonwillard** [comment]
Well, this recent run included the removal of constant caching (i.e. #99), and I don't see any noticeable changes in the speed of the tests.  The claim was that that it would speed up the `MergeOptimizer` (with no measures attached to said claim), so&mdash;worst case scenario&mdash;I was expecting a slowdown that would at least be noticeable in the aggregate.  Alas, I've observed no such slowdown in the tests.

Locally, I'm also not seeing any real changes in memory use.  It obviously wouldn't hurt to directly profile this change, but, given the simplicity now provided by the removal of constant caching, I believe we should move forward with this change.

**Pull request merged**
