### PR TITLE
Quick fix for import issues introduced by #21

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR is a quicker/smaller fix than #54.

### CODE REVIEW

**Comment by twiecki** [comment]
How does this fix the circular import issue?

**Comment by michaelosthege** [comment]
The CI tests look like the import problem appears just on Python 3.6

**Comment by brandonwillard** [comment]
Yes, the problem definitely appears to be in Python 3.6 only.  I've simply reverted the import changes in `opt_uncanonicalize.py` and that appears to work; however, the imports in this library are a complete mess and must be addressed ASAP (see #45).

**Comment by twiecki** [comment]
Nice!!

**Comment by XZLeo** [comment]
I got the same error with python 3.10.

**Comment by allisonmcampbell** [comment]
I also got this error, now with python 3.11

**Comment by ObigerTo** [comment]
I also got the error with my python 3.12. Working in VSC and can't find the solution for it.
Is there a Code which solves the importing Problem?

**Comment by dalesmith8** [comment]
Same error as above, with 3.11.5 - what is going on with this program? I'd rather not switch back to Stan, but...

**Comment by StefanoDamato** [comment]
I am having the same error, using Python 3.9.18 and PyMC3 3.11.4

**Comment by brandonwillard** [comment]
Sorry folks, Aesara is not affiliated with PyMC, so any errors you're having related to PyMC need to be addressed to that project.  

Otherwise, feel free to [open an issue](https://github.com/aesara-devs/aesara/issues/new/choose) for any problems related to the use of Aesara alone.

**Pull request merged**
