### PR TITLE
Add ExtractDiag, Cholesky, and Solve Ops to jaxification

### LINKED ISSUE #49: Missing Op: ExtractDiag
Trying to run a GP model:

```python
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-19-7a2d0b5601fb> in <module>
      1 with model:
----> 2     tr_jax = sample_tfp_nuts(chains=4, target_accept=0.95)

<ipython-input-9-54c111d89074> in sample_tfp_nuts(draws, tune, chains, target_accept, seed, model)
     15 
     16     fgraph = theano.gof.FunctionGraph(model.free_RVs, [model.logpt])
---> 17     fns = theano.sandbox.jaxify.jax_funcify(fgraph)
     18     logp_fn_jax = fns[0]
     19 

~/miniconda3/envs/pymc3theano/lib/python3.8/functools.py in wrapper(*args, **kw)
    873                             '1 positional argument')
    874 
--> 875         return dispatch(args[0].__class__)(*args, **kw)
    876 
    877     funcname = getattr(func, '__name__', 'singledispatch function')

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in jax_funcify_FunctionGraph(fgraph)
    522 
    523     out_nodes = [r.owner for r in fgraph.outputs if r.owner is not None]
--> 524     jax_funcs = [compose_jax_funcs(o, fgraph.inputs) for o in out_nodes]
    525 
    526     return jax_funcs

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in <listcomp>(.0)
    522 
    523     out_nodes = [r.owner for r in fgraph.outputs if r.owner is not None]
--> 524     jax_funcs = [compose_jax_funcs(o, fgraph.inputs) for o in out_nodes]
    525 
    526     return jax_funcs

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
    109             input_f = jax_data_func
    110         else:
--> 111             input_f = compose_jax_funcs(i.owner, fgraph_inputs, memo)
    112 
    113         input_funcs.append(input_f)

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in compose_jax_funcs(out_node, fgraph_inputs, memo)
     90         return memo[out_node]
     91 
---> 92     jax_return_func = jax_funcify(out_node.op)
     93 
     94     input_funcs = []

~/miniconda3/envs/pymc3theano/lib/python3.8/functools.py in wrapper(*args, **kw)
    873                             '1 positional argument')
    874 
--> 875         return dispatch(args[0].__class__)(*args, **kw)
    876 
    877     funcname = getattr(func, '__name__', 'singledispatch function')

~/projects/Theano-PyMC/theano/sandbox/jaxify.py in jax_funcify(op)
    136 def jax_funcify(op):
    137     """Create a JAX "perform" function for a Theano `Variable` and its `Op`."""
--> 138     raise NotImplementedError("No JAX conversion for the given `Op`: {}".format(op))
    139 
    140 

NotImplementedError: No JAX conversion for the given `Op`: ExtractDiag{offset=0, axis1=0, axis2=1, view=False}
```

### PR DESCRIPTION
**Pull request by twiecki**
Closes #49.

### CODE REVIEW

**Review by brandonwillard — CHANGES_REQUESTED** [review]
Looks good, just needs some tests.

**Comment by twiecki** [comment]
Thanks, how do I handle kwargs?

**Comment by brandonwillard** [comment]
> Thanks, how do I handle kwargs?

Which kwargs?  For the `jax` functions?

In general, the `jax` function arguments are going to come from either the arguments to the JAX closure/function constructed in the `Op` dispatch function (e.g. `jax_funcify_ExtractDiag`)&mdash;which themselves are determined by the arguments passed to the `inputs` argument of the `Op`'s `perform` method&mdash;or from fields on the `Op` instance itself.  In the latter case, those fields simply need to be added to the constructed closure/function via reference to the original `Op` object or&mdash;more preferably&mdash;by use of default keyword values in the closure/function (e.g. `def jax_funcify_ExtractDiag(..., axis=op_axis_value)`) where `op_axis_value = op.axis` preceding the function definition).

**Comment by brandonwillard** [comment]
Just pushed some changes.  Needs a few more tests, though.

**Comment by twiecki** [comment]
Added more tests, I think this covers everything. Not sure why the `lower=False` doesn't work.

**Comment by twiecki** [comment]
OK, figured out lower.

**Comment by twiecki** [comment]
Dang, messed up some commits when rebasing. Closing in favor of #59.

**Comment by brandonwillard** [comment]
I think it would be easier if we just wait for the test on this one to finish, merge it, then rebase #59; especially since #59 is behind this branch.

**Review by brandonwillard — APPROVED** [review]

**Pull request closed without merging**
