### PR TITLE
Add Identity Jaxify

### PR DESCRIPTION
**Pull request by junpenglao**

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Test?

**Comment by junpenglao** [comment]
Yeah this one confused me a bit as there is not theano ops call `tt.identity`, I have not completely understand how and where it is used but it does fix some bug with it.

**Comment by brandonwillard** [comment]
> Yeah this one confused me a bit as there is not theano ops call `tt.identity`

This operator is in `theano.scalar.basic` and it likely appears due to composite operators like `theano.tensor.basic.tensor_copy` (i.e. an `Elemwise` with `identity` as the scalar `Op`).

**Comment by junpenglao** [comment]
Since this is (almost) a non-Op, I think I will merge this @twiecki

**Comment by twiecki** [comment]
@junpenglao Well go ahead and try ;).

**Comment by brandonwillard** [comment]
I cannot emphasize enough how we absolutely **cannot** merge PRs without tests (or letting the tests finish)!

**Comment by brandonwillard** [comment]
Also, given the original error (`AttributeError: 'Identity' object has no attribute 'nfunc_spec'`) it looks like the best solution would've been to add an `nfunc_spec` to the `Identity` `Op`.  That way we wouldn't need to include a separate dispatch function for a specific subclass of `Scalar`.

**Pull request merged**
