### PR TITLE
Use jax.lax.cond for IfElse Op

### LINKED ISSUE #178: IfElse JAX conversion should use cond
Related to #177:

The current implementation of the JAX translation for the IfElse op is going to be problematic [because of how JAX handles control flow when `jit`-ing](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-Control-Flow). We should probably be using [`jax.lax.cond`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.cond.html) instead.

### PR DESCRIPTION
**Pull request by eigenfoo**
~~[WIP, will request review when ready.]~~

Closes #178.

cc @dfm @brandonwillard 

The test fails right now, both for the case with `np.array(True)` value, or `tt.dscalar() < 0.5` (with an input value appropriately passed). I've included (the last lines of) the traceback below, and can say that both cases produce similar error messages.

I'm unsure what we want to do here - it still seems to me that the if and else paths must both return the same dtype, which is not the case here. Am I missing something?

<details>
  <summary>Traceback</summary>

```
During handling of the above exception, another exception occurred:

    def test_jax_ifelse():

        import theano.ifelse

        true_vals = np.r_[1, 2, 3]
        false_vals = np.r_[-1, -2, -3]

        x = theano.ifelse.ifelse(np.array(True), true_vals, false_vals)
        x_fg = theano.gof.FunctionGraph([], [x])

>       compare_jax_and_py(x_fg, [])

test_jax.py:473:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_jax.py:59: in compare_jax_and_py
    jax_res = theano_jax_fn(*inputs)
../../theano/compile/function/types.py:974: in __call__
    if output_subset is None
../../theano/gof/link.py:702: in streamline_default_f
    raise_with_op(node, thunk)
../../theano/gof/link.py:343: in raise_with_op
    raise exc_value.with_traceback(exc_trace)
../../theano/gof/link.py:698: in streamline_default_f
    thunk()
../../theano/sandbox/jax_linker.py:88: in thunk
    for jax_impl_jit in jax_impl_jits
../../theano/sandbox/jax_linker.py:88: in <listcomp>
    for jax_impl_jit in jax_impl_jits
../../theano-venv/lib/python3.7/site-packages/jax/traceback_util.py:133: in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
../../theano-venv/lib/python3.7/site-packages/jax/api.py:223: in f_jitted
    donated_invars=donated_invars)
../../theano-venv/lib/python3.7/site-packages/jax/core.py:1177: in bind
    return call_bind(self, fun, *args, **params)
../../theano-venv/lib/python3.7/site-packages/jax/core.py:1630: in call_bind
    outs = primitive.impl(fun, *args, **params)
../../theano-venv/lib/python3.7/site-packages/jax/interpreters/xla.py:557: in _xla_call_impl
    *unsafe_map(arg_spec, args))
../../theano-venv/lib/python3.7/site-packages/jax/linear_util.py:251: in memoized_fun
    ans = call(fun, *args)
../../theano-venv/lib/python3.7/site-packages/jax/interpreters/xla.py:638: in _xla_callable
    fun, pvals, instantiate=False, stage_out=True, bottom=True)  # type: ignore
../../theano-venv/lib/python3.7/site-packages/jax/interpreters/partial_eval.py:1272: in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
../../theano-venv/lib/python3.7/site-packages/jax/linear_util.py:160: in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
../../theano/sandbox/jaxify.py:180: in jax_func
    return return_func(*func_args)
../../theano/sandbox/jaxify.py:537: in ifelse
    operand=None
../../theano-venv/lib/python3.7/site-packages/jax/_src/lax/control_flow.py:665: in cond
    return _cond(*args, **kwargs)
../../theano-venv/lib/python3.7/site-packages/jax/_src/lax/control_flow.py:695: in _cond
    (true_fun, false_fun), ops_tree, ops_avals)
../../theano-venv/lib/python3.7/site-packages/jax/_src/lax/control_flow.py:2628: in _initial_style_jaxprs_with_common_consts
    _initial_style_open_jaxpr(fun, in_tree, in_avals) for fun in funs])
../../theano-venv/lib/python3.7/site-packages/jax/_src/lax/control_flow.py:2628: in <listcomp>
    _initial_style_open_jaxpr(fun, in_tree, in_avals) for fun in funs])
../../theano-venv/lib/python3.7/site-packages/jax/_src/lax/control_flow.py:2608: in _initial_style_open_jaxpr
    wrapped_fun, in_pvals, instantiate=True, stage_out=False)  # type: ignore
../../theano-venv/lib/python3.7/site-packages/jax/interpreters/partial_eval.py:1272: in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
../../theano-venv/lib/python3.7/site-packages/jax/linear_util.py:160: in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
../../theano/sandbox/jaxify.py:535: in <lambda>
    lambda _: jax.lax.cond(n_outs > 1, lambda _: args[:n_outs], lambda _: args[0], operand=None),
../../theano-venv/lib/python3.7/site-packages/jax/_src/lax/control_flow.py:665: in cond
    return _cond(*args, **kwargs)
../../theano-venv/lib/python3.7/site-packages/jax/_src/lax/control_flow.py:701: in _cond
    false_out_tree, false_jaxpr.out_avals)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

what = 'true_fun and false_fun output', tree1 = PyTreeDef(tuple, [*]), avals1 = [ShapedArray(int64[3])], tree2 = *, avals2 = [ShapedArray(int64[3])]

    def _check_tree_and_avals(what, tree1, avals1, tree2, avals2):
      """Raises TypeError if (tree1, avals1) does not match (tree2, avals2).

      Corresponding `tree` and `avals` must match in the sense that the number of
      leaves in `tree` must be equal to the length of `avals`. `what` will be
      prepended to details of the mismatch in TypeError.
      """
      if tree1 != tree2:
        msg = ("{} must have same type structure, got {} and {}.")
>       raise TypeError(msg.format(what, tree1, tree2))
E       TypeError: true_fun and false_fun output must have same type structure, got PyTreeDef(tuple, [*]) and *.
E       Apply node that caused the error: if{}(TensorConstant{True}, TensorConstant{[1 2 3]}, TensorConstant{[-1 -2 -3]})
E       Toposort index: 0
E       Inputs types: [TensorType(bool, scalar), TensorType(int64, vector), TensorType(int64, vector)]
E       Inputs shapes: []
E       Inputs strides: []
E       Inputs values: []
E       Outputs clients: [['output']]
E
E       Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
E         File "/Users/george/Theano-PyMC/theano-venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
E           firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
E         File "/Users/george/Theano-PyMC/theano-venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
E           res = hook_impl.function(*args)
E         File "/Users/george/Theano-PyMC/theano-venv/lib/python3.7/site-packages/_pytest/python.py", line 184, in pytest_pyfunc_call
E           result = testfunction(**testargs)
E         File "/Users/george/Theano-PyMC/tests/sandbox/test_jax.py", line 470, in test_jax_ifelse
E           x = theano.ifelse.ifelse(np.array(True), true_vals, false_vals)
E         File "/Users/george/Theano-PyMC/theano/ifelse.py", line 410, in ifelse
E           rval = new_ifelse(*ins, **dict(return_list=True))
E         File "/Users/george/Theano-PyMC/theano/gof/op.py", line 642, in __call__
E           node = self.make_node(*inputs, **kwargs)
E         File "/Users/george/Theano-PyMC/theano/ifelse.py", line 197, in make_node
E           return Apply(self, [c] + list(args), [t.type() for t in ts])
E         File "/Users/george/Theano-PyMC/theano/ifelse.py", line 197, in <listcomp>
E           return Apply(self, [c] + list(args), [t.type() for t in ts])
E
E       HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```
</details>

### CODE REVIEW

**Comment by dfm** [comment]
Did you try just the following?

```python
        res = jax.lax.cond(
            cond,
            lambda _: args[:n_outs],
            lambda _: args[n_outs:],
            args
        )
```

I don't think that you'll need to have a cond for `n_outs`, that should always be a Python `int`.

**Comment by eigenfoo** [comment]
Sorry, I think there's a misunderstanding here - maybe I wasn't clear.

The original code has the following semantics:

https://github.com/pymc-devs/Theano-PyMC/blob/a9275c3dcc998c8cca5719037e493809b23422ff/theano/sandbox/jaxify.py#L530-L536

If `args = [true_val, false_val] ` and if `n_outs == 1`, then the original code would return `true_val`, and not `[true_val]` (which is what your code snippet would return, since `args[:1]` returns a singleton list `[true_val]`).

My question isn't whether `n_outs` is a Python int (it clearly is) - it's what to do when `n_outs == 1`. To have the same semantics as the original code, we would need to check if `n_outs == 1` and if it is, return the value of that singleton list, instead of the singleton list itself. The problem is that JAX doesn't seem to like that, since (depending on whether `n_outs == 1`), we could return either a value, or a (singleton) list of values, which have different types.

I feel as if this is what the traceback we're getting is trying to say - am I mistaken?

**Comment by dfm** [comment]
You can keep the last line the same:

```python
return res if n_outs > 1 else res[0] 
```

What I was saying is that you don't need those nested `cond`s!

**Comment by dfm** [comment]
I can confirm that the following passes all the tests:

```python
@jax_funcify.register(IfElse)
def jax_funcify_IfElse(op):
    n_outs = op.n_outs

    def ifelse(cond, *args, n_outs=n_outs):
        res = jax.lax.cond(
            cond,
            lambda _: args[:n_outs],
            lambda _: args[n_outs:],
            operand=None
        )
        return res if n_outs > 1 else res[0]

    return ifelse
```

**Comment by eigenfoo** [comment]
Oh interesting, now I'm even more confused - I understood #178 to be about removing _all_ if statements from the Op. What makes the second if statement JIT-able, but the first one not?

(Will update PR soon)

**Comment by dfm** [comment]
Sure! I can explain this and there are more details [in the JAX docs](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-+-JIT).

The difference between the two all comes down to the *type* of the condition. For the `cond` argument, that needs to support theano (or jax) types, because it should support having a *runtime* control flow. For the `n_outs` condition, that is a constant *Python* integer that is set when the op is created and never changed. This means that that conditional only needs to support Python types. In this case, Python `if`s can be jitted just fine because only one branch is *ever* run. As far as JAX is concerned, the other branch doesn't even exist anymore once it's jitted!

It might (or might not!) be useful to think about the fact that we could have equivalently written this implementation as:

```python
@jax_funcify.register(IfElse)
def jax_funcify_IfElse(op):
    n_outs = op.n_outs

    if n_outs > 1:
        def ifelse(cond, *args):
            res = jax.lax.cond(
                cond,
                lambda _: args[:n_outs],
                lambda _: args[n_outs:],
                operand=None
            )
            return res
    else:
        def ifelse(cond, *args):
            res = jax.lax.cond(
                cond,
                lambda _: args[0],
                lambda _: args[1],
                operand=None
            )
            return res

    return ifelse
```

**Comment by eigenfoo** [comment]
Ah I see, thanks for the explanation - that was really clear! I clearly still have a lot to learn about JAX :)

**Pull request merged**
