### PR TITLE
Replacing Travis with GitHub Actions

### LINKED ISSUE #63: Use GitHub Actions
If I'm not mistaken, we can run more jobs in parallel using GitHub Actions and speed up these tests.  For that reason&mdash;and some others (e.g. we can easily perform our deployment automations in Actions, as well), let's switch from Travis to GitHub Actions.

### PR DESCRIPTION
**Pull request by dfm**
This is a work in progress to close #63

### CODE REVIEW

**Comment by brandonwillard** [comment]
Wow, if these times are valid, then running our tests with [GitHub Actions takes roughly 49 minutes of "workflow execution" time](https://github.com/dfm/Theano-PyMC/actions/runs/287250424), while [Travis has been ranging from 1 hour and 27 minutes to 2 hours and 45 minutes of run time (and nearly 5 hours of "total" time)](https://travis-ci.org/github/pymc-devs/Theano-PyMC/pull_requests)!

**Comment by dfm** [comment]
Yep! I think those times will be representative and all the jobs run in parallel!

Do you know why `tests/tensor/test_basic.py::TestInferShape::test_infer_shape` is failing? It's also failing on Travis for my fork.

**Comment by brandonwillard** [comment]
@dfm, if you pull and rebase, the problem should be fixed.

**Comment by dfm** [comment]
OK - I think this is now ready for review!

The most recent run on my form is here: https://github.com/dfm/Theano-PyMC/actions/runs/288180217

And coverage and such is working: https://coveralls.io/github/dfm/Theano-PyMC

**Review by brandonwillard — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
