### PR TITLE
Adding support for building docs on ReadTheDocs

### PR DESCRIPTION
**Pull request by dfm**
This pull request adds support for automatically building the documentation on ReadTheDocs. It looks like it's working, but I'd love to get another set of eyes on it to look for missing pages.

You can take a look at the build docs here: https://theano-pymc-test.readthedocs.io/en/readthedocs/

### CODE REVIEW

**Comment by brandonwillard** [comment]
Do we want to keep the same doc-building setup across all the PyMC projects?  I figured we would at least update the formatting and linting on this project to match the other PyMC projects, but that can be justified by the state of this code base alone.  

Regardless, if RTD makes things simpler, then I'm fine with it.  @twiecki, any thoughts?

**Comment by twiecki** [comment]
Thanks @dfm!

@brandonwillard I think we should go the path of least resistance here and start by just taking over everything we can. But certainly style changes to the code as well as dropping python 2 support are things we can and should do.

**Comment by dfm** [comment]
Thanks all!

@brandonwillard: My thought with this was: I was under the impression that the PyMC3 docs are currently built and deployed manually and avoiding that seemed like a good idea if possible. Happy with whatever others would prefer!

**Comment by twiecki** [comment]
Yeah we never got readthedocs to work, that's pretty much the only reason we don't use it.

**Pull request merged**
