### PR TITLE
Clean config importing

### PR DESCRIPTION
**Pull request by michaelosthege**
This PR continues refactoring of the config, with the ultimate goal of not importing any Theano modules from `configdefaults`.

## Changes
+ `theano.misc.windows` is merged into `theano.utils`
+ `theano.utils.decode` functions were removed (they just wrapped around `str.decode` for no good reason)
+ `scan`-related config parameters are now registered by the `scan` module itself
+ Warning about unused config flags is now a method on the `config` object. It is called from the main Theano `__init__.py` after all submodules were imported (giving them the chance to register config parameters)
+ The registration of two config parameters was moved to `theano.gof.cmodule` because it depends on functions defined there (caused the cyclic import).

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by michaelosthege** [comment]
@twiecki I'm not done yet 😂
I move some more config registration such that `configdefaults` doesn't import `gof`.

**Comment by dfm** [comment]
@michaelosthege: Is it worth fixing #127 here too? Otherwise, I'll plan on doing it after this gets merged.

**Comment by michaelosthege** [comment]
@dfm I'm on Windows and don't have a Mac, so I don't think I can help with #127 here.

**Comment by dfm** [comment]
@michaelosthege: OK - no worries. I'm going to wait until you're finished since #127 requires adding a new default to the config.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
