### PR TITLE
Move linkers to link module

### PR DESCRIPTION
**Pull request by michaelosthege**
Base linker types are going into `theano.link.basic`.

Type annotations on the linkers could help a lot with such refactoring. I suspect they would be relatively clear cut here.

### CODE REVIEW

**Comment by michaelosthege** [comment]
I moved some exception traceback printing functions to `theano.link.debugging`. But I'm not satisfied with that result:

* `raise_with_op` knows about `FunctionGraph` and should therefore be able to import it (✔️ )
* The logic in `__log_thunk_trace` depends on attributes that are monkey-patched onto exception traces by the `CLinker` (😬)

`raise_with_op` is used by other linkers and also `Scan`-related stuff. I guess it should stay in the `link` module then.

After writing this, I think `__log_thunk_trace` should move to `cc.py` where the monkey-patch is done.
And `set_excepthook` can be generalized even further and live in the `utils`, because it just depends on the standard library.

### TODO
+ [ ] generalize `set_exceptionhook` to `utils.add_exceptionhook`
+ [ ] move `__log_thunk_trace` close to `CLinker`
+ [ ] move `raise_with_op` into `theano.link.utils` together with the functions from `theano.link.basic`

**Review by brandonwillard — CHANGES_REQUESTED** [review]
`theano.link.c.vm` looks like it should be in `theano.link` and/or merged with the other core linker code; otherwise, this refactor is a huge improvement.

**Comment by twiecki** [comment]
Nice! Does this require any changes in PyMC3?

**Comment by michaelosthege** [comment]
> Nice! Does this necessitate any changes in PyMC3?

I don't think so. But I also don't know every corner of the PyMC3 codebase..
If, then only minor changes, because this PR was mostly just moving stuff around.

**Pull request merged**
