### PR TITLE
add codecov

### LINKED ISSUE #118: CI should fail on new uncovered lines
We need to set up our CI/Coveralls to fail on newly introduced uncovered lines&mdash;at the very least!

### PR DESCRIPTION
**Pull request by OriolAbril**
Switch to codecov for test coverage reports and checks. Closes #118

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [ ] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [ ] The commits correspond to [relevant logical changes](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes).

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @OriolAbril!

**Comment by dfm** [comment]
It looks to me like this doesn't quite work because codecov still says that the build is pending. For coveralls you need a final step after all the parallel jobs finish to tell them that it's done. Is that not required here?

**Comment by OriolAbril** [comment]
It should not be necessary here, but it may be necessary to give permissions to codecov in order to comment/create checks on the PR which looks like it did not happen

**Comment by OriolAbril** [comment]
Codecov is currently showing this message so it looks like it can't access the repo to report back with the coverage results:

image

@twiecki @brandonwillard according to this message, permissions can be modified from this page: https://github.com/organizations/pymc-devs/settings/installations/3153839

**Comment by brandonwillard** [comment]
Ah, I don't have access to that; it's all on @twiecki.

**Comment by twiecki** [comment]
Should be added.

**Pull request merged**
