### PR TITLE
Merge PureOp and Op

### PR DESCRIPTION
**Pull request by michaelosthege**
Note: The `PureType` and `Type` follow a similar pattern.

All `Op`s now have the C-related methods (only tests and scan used the PureOp directly).

The C-related methods on `Op` are not called from elsewhere. Maybe they could be dispatched into the `Op` type already?

The tests passed locally. I'm open to suggestions what else can/should be refactored next.

### CODE REVIEW

**Comment by brandonwillard** [comment]
FYI: The failure is due to a `Scan` latency test.  It's my impression that something isn't using the C compiled code and that's causing it to be slower than the pure Python implementation and, thus, fail the test.

**Comment by michaelosthege** [comment]
@brandonwillard I'm looking into it. A first clue could be that the coverage of `lazylinker_c.py` went down by a suspicious 43 %.

**Comment by brandonwillard** [comment]
This is yet another example of how badly we need good, direct tests.  That, along with ordered tests, would more clearly tell us what exactly has failed/changed.

**Review by twiecki — APPROVED** [review]

**Comment by brandonwillard** [comment]
FYI: The last commit should've been squashed into the commit before it, since it was simply a change missed by its parent commit.  When we don't squash these "fix" commits, we create unnecessary dependencies between commits.  

More specifically, the `Op`-to-`COp` changes actually exist across _two_ commits&mdash;which is also not obvious or consistent given their descriptions alone&mdash;so anyone attempting to revert/move/cherry pick/etc. will have to know this somehow (or learn it the hard way).

**Pull request merged**
