### PR TITLE
Get rid of singleton design and most module-level variables

### PR DESCRIPTION
**Pull request by michaelosthege**
In both `configparser.py` and `configdefaults.py` several module-level variables were created and in some cases also used from other parts of the codebase.
These module-level globals are not good practice and stand in the way of creating an orthogonal instance of the `TheanoConfigParser` for testing.

While doing this PR I finally understood what the `__get__`/`__set__`-based design is about: The `ConfigParam` objects are assigned as attributes on the `config:TheanoConfigParser` variable and behave like properties.

I managed to refactor all the variables/function into methods on the `TheanoConfigParser`. This way, one can now do the following:

```python
with theano.config.change_flags(...):
    # do stuff

theano.config.get_config_hash()
theano.config.config_print(...)
```

For testing, it would be great to make all instances of `TheanoConfigParser` independent of one another (in contrast to the original singleton design) and orthogonalize the tests.
But because the properties are assigned to the type, this seems impossible unless we switch from property-based `theano.config.floatX` to something else. (For example `theano.config["floatX"]`, but possibly also attributes?).

I'm opening this as draft to get some early feedback. And also to see which tests fail..

### CODE REVIEW

**Comment by michaelosthege** [comment]
ToDo:
+ [ ] don't set `ConfigParam.doc` and `ConfigParam.in_c_key` and other attributes from the `.add` method, but instead pass them directly to the `ConfigParam.__init__`
+ [ ] go through the `TODO` comments
+ [ ] move `config` instance over to `conigdefaults` (The code in `configparser` is very generalized!)
+ [ ] investigate/test what happens when configvars are accessed through an instance of `TheanoConfigParser` that they were not reigstered with

@brandonwillard see the above - let me know if you have thoughts on it

**Comment by brandonwillard** [comment]
That all sounds great!  

Whenever possible, take note of whatever it would take to make all the options changeable at runtime.  That's a real shortcoming that we should look into addressing sometime soon, especially since it would help us simplify testing (e.g. make tests that explicitly target `floatX` values, so we can reduce needless test duplication).

**Comment by michaelosthege** [comment]
@brandonwillard If the pipeline goes ✔️ , I'm done with the ToDos for this PR.
I modified some of them along the way.
We could also take the opportunity to rename the config hashing/printing methods?

With this PR merged, we should create the following issues for removing the deprecated features:
+ **Move `config` instance from `configparser` to `configdefaults`**: All access to the `config` should go through `theano.config` which is the same as `theano.configdefaults.config`.
+ **Remove backwards compatibility of dot-based config access**: The original Theano config supported dot-based section hierarchy. This was replaced with double underscores for better code maintainability.

And the issues should be added to a milestone such that they must be resolved before the big `2.0` release.

**Comment by brandonwillard** [comment]
I restructured the commits slightly and added more `theano.config` reference updates.  I also realized [why those `KeyErrors` are showing up](https://github.com/michaelosthege/Theano-PyMC/blob/objectify-config/theano/configparser.py#L198).  

The underlying `ConfigParser` only takes string values and conversion functions.  We can make a sentinel function and use that as an "unspecified" config value, then follow up later by adding a real (string-based) value.

**Comment by michaelosthege** [comment]
OK, I don't know how to download these changes back to my computer.
But I don't think there is anything left to do either.

**Pull request merged**
