### PR TITLE
Refactor tensor imports

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR performs multiple `theano.tensor`-related refactorings in order to remove both unnecessarily complicated and circular dependencies, as well as generally organize and break apart some of the largest modules.  This work should make it much easier to finish #233, #235, #142, #130, #96.

- [x] Move `TensorType` definitions to `theano.tensor.type` (i.e. where `TensorType` itself is defined).
  - This effectively makes the `theano.tensor.type` module independent of `theano.tensor.basic`, which removes some large and superfluous dependencies between modules.
- [x] Move the math `Op`s in `theano.tensor.basic` into a new `theano.tensor.math` module, effectively leaving only the tensor manipulation, creation, and casting `Op`s in `theano.tensor.basic`.
- [x] Move shape `Op`s out of `theano.compile`.
  - These create some weird and unnecessary dependencies between `theano.tensor` modules and `theano.compile`.  Plus, tensors are the only things with shapes in this library, so why would fundamental shape `Op`s be defined elsewhere?
- [x] Add `__all__`s to `*` imported modules (e.g. `theano.tensor.basic`).
  - This helps prevent the use of indirect imports via `__init__.py`s.
- [x] Move exceptions into their own modules (e.g. `NotScalarConstantError`).
  - One should need to load `theano.tensor.basic`&mdash;and others&mdash;in order to catch exceptions.
- [x] Rename `theano.tensor.nnet.nnet` to `theano.tensor.nnet.basic`.
- [x] Move `theano.scan.utils.clone` to somewhere in `theano.graph`.
  - It's a widely used graph utility function that has nothing (explicitly) to do with `Scan`.
- [x] Move `theano.tensor.basic.bached_dot` to `theano.tensor.blas`
  - `batched_dot` is a helper function for `theano.tensor.blas.BatchedDot`, so it should be defined in the same module.
- [x] Separate math-related optimizations from basic tensor optimizations in `theano.tensor.opt` (same with its corresponding test module).
  - This module is unnecessarily huge and needs to be split up.  It might even make sense to break it into _three_ distinct optimization modules (perhaps in a new `ops` sub-package).
- [x] Move `theano.tensor.basic.[addbroadcast, unbroadcast, patternbroadcast]` to wherever their underlying `Op`s are located (i.e. after the `theano.compile.ops` refactoring above).
- [x] Move `theano.sparse_grad`
  - There doesn't seem to be a reason for this to be defined in `theano.__init__`.  It would make more sense in `theano.sparse`.
- [x] Move `tests.tensor.nnet.test_nnet` sigmoid and softplus tests to `test_sigm`.
- [x] Move `theano.tensor.nnet.[conv2d, conv2d_transpose]` to `theano.tensor.nnet.abstract_conv`.
- [x] Move `theano.pathparse` to `theano.gpuarray`, since that's the only place it's used.
- [x] Rename `theano.tensor.nnet.bn` to `batchnorm`.
- [x] Move `theano.tensor.inc_code` into `theano.tensor.subtensor`, since that's the only place it's used.
- [x] Move `theano.tensor.opt.MakeVector` to `theano.tensor.basic`.

### CODE REVIEW

**Comment by brandonwillard** [comment]
Reminder: after merging this PR, the release should at least be another minor version up.

**Comment by twiecki** [comment]
Will this require PyMC3 changes?

**Comment by brandonwillard** [comment]
> Will this require PyMC3 changes?

It will most likely require some small import and reference name changes.

**Comment by michaelosthege** [comment]
@brandonwillard let us know if there's anything you can be helped with. The task list is really long for a single PR..

**Comment by brandonwillard** [comment]
After this passes, we can merge.

**Comment by twiecki** [comment]
This is a big one!

**Comment by michaelosthege** [comment]
Yes, I just finished reviewing too. Saying I had read every line of the diff would be a lie, but I did read all the commits and checked out diffs here and there.

Great work!

**Pull request merged**
