### PR TITLE
Update Travis infrastructure to Python 3.6/3.7 and current numpy

### PR DESCRIPTION
**Pull request by dfm**
This pull request merges the current master branch of Theano (especially https://github.com/Theano/Theano/pull/6749), fixes a few imports from `numpy.testing`, and updates the `.travis.yml` config to run on the current Python and numpy versions that PyMC3 targets. With these changes, all the tests appear to run and pass. Take a look and let me know if there are any suggestions.

### CODE REVIEW

**Comment by dfm** [comment]
PS. I'll squash all those travis-debugging commits when the time comes :)

**Comment by dfm** [comment]
#9 should be merged first.

**Comment by dfm** [comment]
I should also mention that this solves #6

**Comment by twiecki** [comment]
This is great!

@brandonwillard I went ahead and squash-merged using the github functionality.

**Pull request merged**
