### PR TITLE
Remove string compat

### PR DESCRIPTION
**Pull request by eigenfoo**
Supercedes https://github.com/pymc-devs/Theano-PyMC/pull/144

### CODE REVIEW

**Comment by eigenfoo** [comment]
Between the sheer number of files this PR touches, the edge cases where f-strings are suboptimal for our purposes, (and, admittedly, my flagging interest in continuing to work on this), I'm prepared to call this a contribution - if/when all tests pass, I'd prefer to merge this and open follow-up issues, rather than continue to work on this PR.

**Comment by brandonwillard** [comment]
@eigenfoo, did you select ["Allow edits from maintainers"](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on this PR?  

If not, enable it and I'll push some changes to this branch that cover the remaining f-strings (e.g. in `scalar/basic.py` and `elemwise_cgen.py`) and clean up the commits.

**Comment by eigenfoo** [comment]
@brandonwillard just enabled the setting.

**Comment by eigenfoo** [comment]
Thanks for pushing this over the finish line @brandonwillard!

**Comment by brandonwillard** [comment]
No problem.  In general, I don't like making such large single commits, but, for the sake of time and effort, this seemed like the way to go.  Also, the effect of running an automated tool definitely makes for a single logical change/commit, so there isn't really a problem there.  It might've been nicer to break it up into per-file changes, though.

**Pull request merged**
