### PR TITLE
Stop importing test suite from __init__

### LINKED ISSUE #84: Theano top-level tests module is not resolved when running coverage on a different project that has a "tests" module
I wanted to run the tests on our `calibr8` package, but `import Theano` blew up on this line:
https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/__init__.py#L170

I can `import theano` from a jupyter notebook without problems so it must be related to some changes that `coverage` does to the path variables.

Nevertheless the problem did not appear with the original Theano.

Explanation of the traceback: `calibr8.utils` imports `theano`, but `theano` imports `tests` which is a directory in our project. The code in `tests/test.py` imports a class (from the core module) that is defined *after* `import theano`.

```
Traceback (most recent call last):
  File "tests/tests.py", line 9, in <module>
    import calibr8
  File "c:\users\osthege\repos\calibr8\calibr8\calibr8\__init__.py", line 1, in <module>
    from . core import  *
  File "c:\users\osthege\repos\calibr8\calibr8\calibr8\core.py", line 10, in <module>
    from . import utils
  File "c:\users\osthege\repos\calibr8\calibr8\calibr8\utils.py", line 10, in <module>
    import theano
  File "c:\users\osthege\repos\theano-pymc\theano\__init__.py", line 170, in <module>
    import tests
  File "C:\Users\osthege\Repos\calibr8\calibr8\tests\tests.py", line 30, in <module>
    class _TestModel(calibr8.ErrorModel):
AttributeError: module 'calibr8' has no attribute 'ErrorModel'
```

### PR DESCRIPTION
**Pull request by michaelosthege**
My understanding of best practice is that the tests should live either in their own folder outside of the actual package (that's the case now) or as a submodule that is not imported from the actual package modules.

The `import tests` line conflicts with both of the above.

+ the 6-year old comment indicated that the import was done because of some GPU configuration, without providing any details
+ the import actually imported the first thing called "tests" that is found in the PATH, causing #84 

If just removing the import doesn't work because they are too entangled, we should move the tests into a submodule?

closes #84

### CODE REVIEW

**Comment by twiecki** [comment]
This makes sense to me but I'm worried we're breaking GPU and we have no tests for this. Do you know which config gets set?

**Comment by michaelosthege** [comment]
> This makes sense to me but I'm worried we're breaking GPU and we have no tests for this. Do you know which config gets set?

I don't know. Also there are 180 files in the `tests` dir so I gave up looking for it right away.
In line 179 the `gpuarray` submodule is imported so it might be related to that.

Do we know if GPU works?

Also, I can move the `import tests` into the `if` clause and/or raise a warning, so the next person looking into GPU support becomes aware of it?

**Comment by brandonwillard** [comment]
The `tests/__init__.py` is empty, so it doesn't look like that `import tests` is auto-loading anything.  

The next consideration would be for imports like `from theano import tests` and attribute references like `theano.tests` within the `theano` package.  Regarding those, I could find anything.

I did find some some broken imports from a non-existent `tests.theano` in `theano.sparse.sandbox`, but those are unrelated to #84.

**Review by brandonwillard — DISMISSED** [review]

**Review by brandonwillard — APPROVED** [review]
After going through all the possible `tests` imports in the project, it looks like there was one dependency between `tests` and `theano.gpuarray.opt`.  It involved the `PdbBreakpoint` `Op` (previously) defined in `tests.breakpoint`.  

Oddly, that requirement was directly imported from `tests and&mdash;as a result&mdash;didn't involve the `theano.tests` module in question, unless you view the `theano.tests` import as an initial check for the availability of the `tests` module.  Given the old organization of the project, that wouldn't surprise me, so I'm assuming that was the only meaningful connection left.

**Pull request merged**
